database:

  # [REQUIRED] An absolute path to the SQLite database that is used to store messages.
  database_url: /home/pi/sms-database.db

  # [REQUIRED] 32 byte encryption key, base-64 encoded. This is used to encrypt message content within the database
  encryption_key: ...

modem:

  # The modem serial device path.
  device: /dev/ttyS0

  # The baud rate to use when creating device connection.
  baud: 115200

  # How many milliseconds between reads to the modem connection. This effectively determines the API response times.
  # Lower values mean a faster response, but with more CPU overhead. This should remain 20 to 60ms.
  read_interval_duration: 30

  # Buffer size for Modem command sender channel. This is bound to ensure that slow command responses don't result in
  # unexpected backpressure as we keep adding new commands to the queue. If the queue is full, API requests are rejected.
  cmd_channel_buffer_size: 32

http:

  # If the HTTP server should be started. By default, this is false. Without the HTTP server, this effectively just
  # becomes an SMS reciever which can use the webhooks to forward them since the HTTP API is required for sending.
  enabled: true

  # The bind address used for the HTTP TcpListener.
  address: 0.0.0.0:3000

webhooks:

  # By default, a webhook with only a URL will receive only "Incoming" events with no additional headers.
  # The URL is the only required field for a webhook!
  - url: https://webhook-a.example.org

  # Arbitrary additional headers, such as Authorization can be added to requests.
  - url: https://webhook-b.example.org
    headers:
      Authorization: test
      X-Other: hello

  # Specific events can be selected for webhooks to ensure only relevant information is received.
  - url: https://webhook-c.example.org
    events:
      - incoming
      - outgoing
      - delivery
